//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace SmallInvestment.PhoneWeb.SmallInvestmentWs {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankEntity", Namespace="http://tempuri.org/")]
    public partial class BankEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int BankIDField;
        
        private string BankNameField;
        
        private string BankGroupField;
        
        private int CurrentRadioField;
        
        private int Radio3mField;
        
        private int Radio6mField;
        
        private int Radio1yField;
        
        private int Radio2yField;
        
        private int Radio3yField;
        
        private int Radio5yField;
        
        private int Disperse_1yRadioField;
        
        private int Disperse_3yRadioField;
        
        private int Disperse_5yRadioField;
        
        private string MetroColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BankID {
            get {
                return this.BankIDField;
            }
            set {
                if ((this.BankIDField.Equals(value) != true)) {
                    this.BankIDField = value;
                    this.RaisePropertyChanged("BankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BankGroup {
            get {
                return this.BankGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.BankGroupField, value) != true)) {
                    this.BankGroupField = value;
                    this.RaisePropertyChanged("BankGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CurrentRadio {
            get {
                return this.CurrentRadioField;
            }
            set {
                if ((this.CurrentRadioField.Equals(value) != true)) {
                    this.CurrentRadioField = value;
                    this.RaisePropertyChanged("CurrentRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Radio3m {
            get {
                return this.Radio3mField;
            }
            set {
                if ((this.Radio3mField.Equals(value) != true)) {
                    this.Radio3mField = value;
                    this.RaisePropertyChanged("Radio3m");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Radio6m {
            get {
                return this.Radio6mField;
            }
            set {
                if ((this.Radio6mField.Equals(value) != true)) {
                    this.Radio6mField = value;
                    this.RaisePropertyChanged("Radio6m");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Radio1y {
            get {
                return this.Radio1yField;
            }
            set {
                if ((this.Radio1yField.Equals(value) != true)) {
                    this.Radio1yField = value;
                    this.RaisePropertyChanged("Radio1y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Radio2y {
            get {
                return this.Radio2yField;
            }
            set {
                if ((this.Radio2yField.Equals(value) != true)) {
                    this.Radio2yField = value;
                    this.RaisePropertyChanged("Radio2y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Radio3y {
            get {
                return this.Radio3yField;
            }
            set {
                if ((this.Radio3yField.Equals(value) != true)) {
                    this.Radio3yField = value;
                    this.RaisePropertyChanged("Radio3y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int Radio5y {
            get {
                return this.Radio5yField;
            }
            set {
                if ((this.Radio5yField.Equals(value) != true)) {
                    this.Radio5yField = value;
                    this.RaisePropertyChanged("Radio5y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int Disperse_1yRadio {
            get {
                return this.Disperse_1yRadioField;
            }
            set {
                if ((this.Disperse_1yRadioField.Equals(value) != true)) {
                    this.Disperse_1yRadioField = value;
                    this.RaisePropertyChanged("Disperse_1yRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int Disperse_3yRadio {
            get {
                return this.Disperse_3yRadioField;
            }
            set {
                if ((this.Disperse_3yRadioField.Equals(value) != true)) {
                    this.Disperse_3yRadioField = value;
                    this.RaisePropertyChanged("Disperse_3yRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Disperse_5yRadio {
            get {
                return this.Disperse_5yRadioField;
            }
            set {
                if ((this.Disperse_5yRadioField.Equals(value) != true)) {
                    this.Disperse_5yRadioField = value;
                    this.RaisePropertyChanged("Disperse_5yRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string MetroColor {
            get {
                return this.MetroColorField;
            }
            set {
                if ((object.ReferenceEquals(this.MetroColorField, value) != true)) {
                    this.MetroColorField = value;
                    this.RaisePropertyChanged("MetroColor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanRateEntity", Namespace="http://tempuri.org/")]
    public partial class LoanRateEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private int LoanRateField;
        
        private string LoanRateNameField;
        
        private int LoanRate6MField;
        
        private int LoanRate1YField;
        
        private int LoanRate1To3YField;
        
        private int LoanRate3To5YField;
        
        private int LoanRate5YAboveField;
        
        private int HouseFundLoan5YField;
        
        private int HouseFundLoan5YAboveField;
        
        private int StateField;
        
        private int FlagField;
        
        private int OrderFlagField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LoanRate {
            get {
                return this.LoanRateField;
            }
            set {
                if ((this.LoanRateField.Equals(value) != true)) {
                    this.LoanRateField = value;
                    this.RaisePropertyChanged("LoanRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoanRateName {
            get {
                return this.LoanRateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanRateNameField, value) != true)) {
                    this.LoanRateNameField = value;
                    this.RaisePropertyChanged("LoanRateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int LoanRate6M {
            get {
                return this.LoanRate6MField;
            }
            set {
                if ((this.LoanRate6MField.Equals(value) != true)) {
                    this.LoanRate6MField = value;
                    this.RaisePropertyChanged("LoanRate6M");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int LoanRate1Y {
            get {
                return this.LoanRate1YField;
            }
            set {
                if ((this.LoanRate1YField.Equals(value) != true)) {
                    this.LoanRate1YField = value;
                    this.RaisePropertyChanged("LoanRate1Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int LoanRate1To3Y {
            get {
                return this.LoanRate1To3YField;
            }
            set {
                if ((this.LoanRate1To3YField.Equals(value) != true)) {
                    this.LoanRate1To3YField = value;
                    this.RaisePropertyChanged("LoanRate1To3Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int LoanRate3To5Y {
            get {
                return this.LoanRate3To5YField;
            }
            set {
                if ((this.LoanRate3To5YField.Equals(value) != true)) {
                    this.LoanRate3To5YField = value;
                    this.RaisePropertyChanged("LoanRate3To5Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int LoanRate5YAbove {
            get {
                return this.LoanRate5YAboveField;
            }
            set {
                if ((this.LoanRate5YAboveField.Equals(value) != true)) {
                    this.LoanRate5YAboveField = value;
                    this.RaisePropertyChanged("LoanRate5YAbove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int HouseFundLoan5Y {
            get {
                return this.HouseFundLoan5YField;
            }
            set {
                if ((this.HouseFundLoan5YField.Equals(value) != true)) {
                    this.HouseFundLoan5YField = value;
                    this.RaisePropertyChanged("HouseFundLoan5Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int HouseFundLoan5YAbove {
            get {
                return this.HouseFundLoan5YAboveField;
            }
            set {
                if ((this.HouseFundLoan5YAboveField.Equals(value) != true)) {
                    this.HouseFundLoan5YAboveField = value;
                    this.RaisePropertyChanged("HouseFundLoan5YAbove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int Flag {
            get {
                return this.FlagField;
            }
            set {
                if ((this.FlagField.Equals(value) != true)) {
                    this.FlagField = value;
                    this.RaisePropertyChanged("Flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int OrderFlag {
            get {
                return this.OrderFlagField;
            }
            set {
                if ((this.OrderFlagField.Equals(value) != true)) {
                    this.OrderFlagField = value;
                    this.RaisePropertyChanged("OrderFlag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WageEntity", Namespace="http://tempuri.org/")]
    public partial class WageEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private string CityField;
        
        private string CityGroupField;
        
        private float HousingFundRadioField;
        
        private float HousingFundCompayRadioField;
        
        private float MedicareFundRadioField;
        
        private float MedicareFundCompanyRadioField;
        
        private float UnemploymentFundRadioField;
        
        private float UnemploymentFundCompanyRadioField;
        
        private float EndowmentFundRadioField;
        
        private float EndowmentFundCompanyRadioField;
        
        private float InjuryFundRadioField;
        
        private float InjuryFundCompanyRadioField;
        
        private float BirthFundRadioField;
        
        private float BirthFundCompanyRadioField;
        
        private int MaxWageField;
        
        private int MinWageField;
        
        private int StatusField;
        
        private System.DateTime CDateField;
        
        private string MetroColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CityGroup {
            get {
                return this.CityGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.CityGroupField, value) != true)) {
                    this.CityGroupField = value;
                    this.RaisePropertyChanged("CityGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float HousingFundRadio {
            get {
                return this.HousingFundRadioField;
            }
            set {
                if ((this.HousingFundRadioField.Equals(value) != true)) {
                    this.HousingFundRadioField = value;
                    this.RaisePropertyChanged("HousingFundRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float HousingFundCompayRadio {
            get {
                return this.HousingFundCompayRadioField;
            }
            set {
                if ((this.HousingFundCompayRadioField.Equals(value) != true)) {
                    this.HousingFundCompayRadioField = value;
                    this.RaisePropertyChanged("HousingFundCompayRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public float MedicareFundRadio {
            get {
                return this.MedicareFundRadioField;
            }
            set {
                if ((this.MedicareFundRadioField.Equals(value) != true)) {
                    this.MedicareFundRadioField = value;
                    this.RaisePropertyChanged("MedicareFundRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public float MedicareFundCompanyRadio {
            get {
                return this.MedicareFundCompanyRadioField;
            }
            set {
                if ((this.MedicareFundCompanyRadioField.Equals(value) != true)) {
                    this.MedicareFundCompanyRadioField = value;
                    this.RaisePropertyChanged("MedicareFundCompanyRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public float UnemploymentFundRadio {
            get {
                return this.UnemploymentFundRadioField;
            }
            set {
                if ((this.UnemploymentFundRadioField.Equals(value) != true)) {
                    this.UnemploymentFundRadioField = value;
                    this.RaisePropertyChanged("UnemploymentFundRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public float UnemploymentFundCompanyRadio {
            get {
                return this.UnemploymentFundCompanyRadioField;
            }
            set {
                if ((this.UnemploymentFundCompanyRadioField.Equals(value) != true)) {
                    this.UnemploymentFundCompanyRadioField = value;
                    this.RaisePropertyChanged("UnemploymentFundCompanyRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public float EndowmentFundRadio {
            get {
                return this.EndowmentFundRadioField;
            }
            set {
                if ((this.EndowmentFundRadioField.Equals(value) != true)) {
                    this.EndowmentFundRadioField = value;
                    this.RaisePropertyChanged("EndowmentFundRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public float EndowmentFundCompanyRadio {
            get {
                return this.EndowmentFundCompanyRadioField;
            }
            set {
                if ((this.EndowmentFundCompanyRadioField.Equals(value) != true)) {
                    this.EndowmentFundCompanyRadioField = value;
                    this.RaisePropertyChanged("EndowmentFundCompanyRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public float InjuryFundRadio {
            get {
                return this.InjuryFundRadioField;
            }
            set {
                if ((this.InjuryFundRadioField.Equals(value) != true)) {
                    this.InjuryFundRadioField = value;
                    this.RaisePropertyChanged("InjuryFundRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public float InjuryFundCompanyRadio {
            get {
                return this.InjuryFundCompanyRadioField;
            }
            set {
                if ((this.InjuryFundCompanyRadioField.Equals(value) != true)) {
                    this.InjuryFundCompanyRadioField = value;
                    this.RaisePropertyChanged("InjuryFundCompanyRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public float BirthFundRadio {
            get {
                return this.BirthFundRadioField;
            }
            set {
                if ((this.BirthFundRadioField.Equals(value) != true)) {
                    this.BirthFundRadioField = value;
                    this.RaisePropertyChanged("BirthFundRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public float BirthFundCompanyRadio {
            get {
                return this.BirthFundCompanyRadioField;
            }
            set {
                if ((this.BirthFundCompanyRadioField.Equals(value) != true)) {
                    this.BirthFundCompanyRadioField = value;
                    this.RaisePropertyChanged("BirthFundCompanyRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int MaxWage {
            get {
                return this.MaxWageField;
            }
            set {
                if ((this.MaxWageField.Equals(value) != true)) {
                    this.MaxWageField = value;
                    this.RaisePropertyChanged("MaxWage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int MinWage {
            get {
                return this.MinWageField;
            }
            set {
                if ((this.MinWageField.Equals(value) != true)) {
                    this.MinWageField = value;
                    this.RaisePropertyChanged("MinWage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.DateTime CDate {
            get {
                return this.CDateField;
            }
            set {
                if ((this.CDateField.Equals(value) != true)) {
                    this.CDateField = value;
                    this.RaisePropertyChanged("CDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string MetroColor {
            get {
                return this.MetroColorField;
            }
            set {
                if ((object.ReferenceEquals(this.MetroColorField, value) != true)) {
                    this.MetroColorField = value;
                    this.RaisePropertyChanged("MetroColor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Guide", Namespace="http://tempuri.org/")]
    public partial class Guide : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private int OrderFlagField;
        
        private string TitleField;
        
        private string ImageUrlField;
        
        private string DescField;
        
        private string ContentUrlField;
        
        private string StateField;
        
        private string GroupNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderFlag {
            get {
                return this.OrderFlagField;
            }
            set {
                if ((this.OrderFlagField.Equals(value) != true)) {
                    this.OrderFlagField = value;
                    this.RaisePropertyChanged("OrderFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ContentUrl {
            get {
                return this.ContentUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentUrlField, value) != true)) {
                    this.ContentUrlField = value;
                    this.RaisePropertyChanged("ContentUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmallInvestmentWs.SmallInWbsSoap")]
    public interface SmallInWbsSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetBankList", ReplyAction="*")]
        System.IAsyncResult BeginGetBankList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListRequest request, System.AsyncCallback callback, object asyncState);
        
        SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListResponse EndGetBankList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetLoanRateList", ReplyAction="*")]
        System.IAsyncResult BeginGetLoanRateList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListRequest request, System.AsyncCallback callback, object asyncState);
        
        SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListResponse EndGetLoanRateList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetWageList", ReplyAction="*")]
        System.IAsyncResult BeginGetWageList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListRequest request, System.AsyncCallback callback, object asyncState);
        
        SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListResponse EndGetWageList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetGuideList", ReplyAction="*")]
        System.IAsyncResult BeginGetGuideList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListRequest request, System.AsyncCallback callback, object asyncState);
        
        SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListResponse EndGetGuideList(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBankListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBankList", Namespace="http://tempuri.org/", Order=0)]
        public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListRequestBody Body;
        
        public GetBankListRequest() {
        }
        
        public GetBankListRequest(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBankListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passStr;
        
        public GetBankListRequestBody() {
        }
        
        public GetBankListRequestBody(string passStr) {
            this.passStr = passStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBankListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBankListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListResponseBody Body;
        
        public GetBankListResponse() {
        }
        
        public GetBankListResponse(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBankListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.BankEntity> GetBankListResult;
        
        public GetBankListResponseBody() {
        }
        
        public GetBankListResponseBody(System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.BankEntity> GetBankListResult) {
            this.GetBankListResult = GetBankListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoanRateListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoanRateList", Namespace="http://tempuri.org/", Order=0)]
        public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListRequestBody Body;
        
        public GetLoanRateListRequest() {
        }
        
        public GetLoanRateListRequest(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoanRateListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passStr;
        
        public GetLoanRateListRequestBody() {
        }
        
        public GetLoanRateListRequestBody(string passStr) {
            this.passStr = passStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoanRateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoanRateListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListResponseBody Body;
        
        public GetLoanRateListResponse() {
        }
        
        public GetLoanRateListResponse(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoanRateListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.LoanRateEntity> GetLoanRateListResult;
        
        public GetLoanRateListResponseBody() {
        }
        
        public GetLoanRateListResponseBody(System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.LoanRateEntity> GetLoanRateListResult) {
            this.GetLoanRateListResult = GetLoanRateListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWageListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWageList", Namespace="http://tempuri.org/", Order=0)]
        public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListRequestBody Body;
        
        public GetWageListRequest() {
        }
        
        public GetWageListRequest(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWageListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passStr;
        
        public GetWageListRequestBody() {
        }
        
        public GetWageListRequestBody(string passStr) {
            this.passStr = passStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWageListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWageListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListResponseBody Body;
        
        public GetWageListResponse() {
        }
        
        public GetWageListResponse(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWageListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.WageEntity> GetWageListResult;
        
        public GetWageListResponseBody() {
        }
        
        public GetWageListResponseBody(System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.WageEntity> GetWageListResult) {
            this.GetWageListResult = GetWageListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGuideListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGuideList", Namespace="http://tempuri.org/", Order=0)]
        public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListRequestBody Body;
        
        public GetGuideListRequest() {
        }
        
        public GetGuideListRequest(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGuideListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passStr;
        
        public GetGuideListRequestBody() {
        }
        
        public GetGuideListRequestBody(string passStr) {
            this.passStr = passStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGuideListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGuideListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListResponseBody Body;
        
        public GetGuideListResponse() {
        }
        
        public GetGuideListResponse(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGuideListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.Guide> GetGuideListResult;
        
        public GetGuideListResponseBody() {
        }
        
        public GetGuideListResponseBody(System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.Guide> GetGuideListResult) {
            this.GetGuideListResult = GetGuideListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmallInWbsSoapChannel : SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBankListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBankListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.BankEntity> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.BankEntity>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLoanRateListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLoanRateListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.LoanRateEntity> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.LoanRateEntity>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWageListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWageListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.WageEntity> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.WageEntity>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGuideListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetGuideListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.Guide> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.Guide>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmallInWbsSoapClient : System.ServiceModel.ClientBase<SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap>, SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap {
        
        private BeginOperationDelegate onBeginGetBankListDelegate;
        
        private EndOperationDelegate onEndGetBankListDelegate;
        
        private System.Threading.SendOrPostCallback onGetBankListCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLoanRateListDelegate;
        
        private EndOperationDelegate onEndGetLoanRateListDelegate;
        
        private System.Threading.SendOrPostCallback onGetLoanRateListCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWageListDelegate;
        
        private EndOperationDelegate onEndGetWageListDelegate;
        
        private System.Threading.SendOrPostCallback onGetWageListCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetGuideListDelegate;
        
        private EndOperationDelegate onEndGetGuideListDelegate;
        
        private System.Threading.SendOrPostCallback onGetGuideListCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SmallInWbsSoapClient() {
        }
        
        public SmallInWbsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmallInWbsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmallInWbsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmallInWbsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetBankListCompletedEventArgs> GetBankListCompleted;
        
        public event System.EventHandler<GetLoanRateListCompletedEventArgs> GetLoanRateListCompleted;
        
        public event System.EventHandler<GetWageListCompletedEventArgs> GetWageListCompleted;
        
        public event System.EventHandler<GetGuideListCompletedEventArgs> GetGuideListCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap.BeginGetBankList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBankList(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetBankList(string passStr, System.AsyncCallback callback, object asyncState) {
            SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListRequest inValue = new SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListRequest();
            inValue.Body = new SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListRequestBody();
            inValue.Body.passStr = passStr;
            return ((SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap)(this)).BeginGetBankList(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListResponse SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap.EndGetBankList(System.IAsyncResult result) {
            return base.Channel.EndGetBankList(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.BankEntity> EndGetBankList(System.IAsyncResult result) {
            SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListResponse retVal = ((SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap)(this)).EndGetBankList(result);
            return retVal.Body.GetBankListResult;
        }
        
        private System.IAsyncResult OnBeginGetBankList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string passStr = ((string)(inValues[0]));
            return this.BeginGetBankList(passStr, callback, asyncState);
        }
        
        private object[] OnEndGetBankList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.BankEntity> retVal = this.EndGetBankList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBankListCompleted(object state) {
            if ((this.GetBankListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBankListCompleted(this, new GetBankListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBankListAsync(string passStr) {
            this.GetBankListAsync(passStr, null);
        }
        
        public void GetBankListAsync(string passStr, object userState) {
            if ((this.onBeginGetBankListDelegate == null)) {
                this.onBeginGetBankListDelegate = new BeginOperationDelegate(this.OnBeginGetBankList);
            }
            if ((this.onEndGetBankListDelegate == null)) {
                this.onEndGetBankListDelegate = new EndOperationDelegate(this.OnEndGetBankList);
            }
            if ((this.onGetBankListCompletedDelegate == null)) {
                this.onGetBankListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBankListCompleted);
            }
            base.InvokeAsync(this.onBeginGetBankListDelegate, new object[] {
                        passStr}, this.onEndGetBankListDelegate, this.onGetBankListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap.BeginGetLoanRateList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLoanRateList(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetLoanRateList(string passStr, System.AsyncCallback callback, object asyncState) {
            SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListRequest inValue = new SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListRequest();
            inValue.Body = new SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListRequestBody();
            inValue.Body.passStr = passStr;
            return ((SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap)(this)).BeginGetLoanRateList(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListResponse SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap.EndGetLoanRateList(System.IAsyncResult result) {
            return base.Channel.EndGetLoanRateList(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.LoanRateEntity> EndGetLoanRateList(System.IAsyncResult result) {
            SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListResponse retVal = ((SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap)(this)).EndGetLoanRateList(result);
            return retVal.Body.GetLoanRateListResult;
        }
        
        private System.IAsyncResult OnBeginGetLoanRateList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string passStr = ((string)(inValues[0]));
            return this.BeginGetLoanRateList(passStr, callback, asyncState);
        }
        
        private object[] OnEndGetLoanRateList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.LoanRateEntity> retVal = this.EndGetLoanRateList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLoanRateListCompleted(object state) {
            if ((this.GetLoanRateListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLoanRateListCompleted(this, new GetLoanRateListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLoanRateListAsync(string passStr) {
            this.GetLoanRateListAsync(passStr, null);
        }
        
        public void GetLoanRateListAsync(string passStr, object userState) {
            if ((this.onBeginGetLoanRateListDelegate == null)) {
                this.onBeginGetLoanRateListDelegate = new BeginOperationDelegate(this.OnBeginGetLoanRateList);
            }
            if ((this.onEndGetLoanRateListDelegate == null)) {
                this.onEndGetLoanRateListDelegate = new EndOperationDelegate(this.OnEndGetLoanRateList);
            }
            if ((this.onGetLoanRateListCompletedDelegate == null)) {
                this.onGetLoanRateListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLoanRateListCompleted);
            }
            base.InvokeAsync(this.onBeginGetLoanRateListDelegate, new object[] {
                        passStr}, this.onEndGetLoanRateListDelegate, this.onGetLoanRateListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap.BeginGetWageList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWageList(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetWageList(string passStr, System.AsyncCallback callback, object asyncState) {
            SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListRequest inValue = new SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListRequest();
            inValue.Body = new SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListRequestBody();
            inValue.Body.passStr = passStr;
            return ((SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap)(this)).BeginGetWageList(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListResponse SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap.EndGetWageList(System.IAsyncResult result) {
            return base.Channel.EndGetWageList(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.WageEntity> EndGetWageList(System.IAsyncResult result) {
            SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListResponse retVal = ((SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap)(this)).EndGetWageList(result);
            return retVal.Body.GetWageListResult;
        }
        
        private System.IAsyncResult OnBeginGetWageList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string passStr = ((string)(inValues[0]));
            return this.BeginGetWageList(passStr, callback, asyncState);
        }
        
        private object[] OnEndGetWageList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.WageEntity> retVal = this.EndGetWageList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWageListCompleted(object state) {
            if ((this.GetWageListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWageListCompleted(this, new GetWageListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWageListAsync(string passStr) {
            this.GetWageListAsync(passStr, null);
        }
        
        public void GetWageListAsync(string passStr, object userState) {
            if ((this.onBeginGetWageListDelegate == null)) {
                this.onBeginGetWageListDelegate = new BeginOperationDelegate(this.OnBeginGetWageList);
            }
            if ((this.onEndGetWageListDelegate == null)) {
                this.onEndGetWageListDelegate = new EndOperationDelegate(this.OnEndGetWageList);
            }
            if ((this.onGetWageListCompletedDelegate == null)) {
                this.onGetWageListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWageListCompleted);
            }
            base.InvokeAsync(this.onBeginGetWageListDelegate, new object[] {
                        passStr}, this.onEndGetWageListDelegate, this.onGetWageListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap.BeginGetGuideList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetGuideList(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetGuideList(string passStr, System.AsyncCallback callback, object asyncState) {
            SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListRequest inValue = new SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListRequest();
            inValue.Body = new SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListRequestBody();
            inValue.Body.passStr = passStr;
            return ((SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap)(this)).BeginGetGuideList(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListResponse SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap.EndGetGuideList(System.IAsyncResult result) {
            return base.Channel.EndGetGuideList(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.Guide> EndGetGuideList(System.IAsyncResult result) {
            SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListResponse retVal = ((SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap)(this)).EndGetGuideList(result);
            return retVal.Body.GetGuideListResult;
        }
        
        private System.IAsyncResult OnBeginGetGuideList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string passStr = ((string)(inValues[0]));
            return this.BeginGetGuideList(passStr, callback, asyncState);
        }
        
        private object[] OnEndGetGuideList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SmallInvestment.PhoneWeb.SmallInvestmentWs.Guide> retVal = this.EndGetGuideList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetGuideListCompleted(object state) {
            if ((this.GetGuideListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetGuideListCompleted(this, new GetGuideListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetGuideListAsync(string passStr) {
            this.GetGuideListAsync(passStr, null);
        }
        
        public void GetGuideListAsync(string passStr, object userState) {
            if ((this.onBeginGetGuideListDelegate == null)) {
                this.onBeginGetGuideListDelegate = new BeginOperationDelegate(this.OnBeginGetGuideList);
            }
            if ((this.onEndGetGuideListDelegate == null)) {
                this.onEndGetGuideListDelegate = new EndOperationDelegate(this.OnEndGetGuideList);
            }
            if ((this.onGetGuideListCompletedDelegate == null)) {
                this.onGetGuideListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetGuideListCompleted);
            }
            base.InvokeAsync(this.onBeginGetGuideListDelegate, new object[] {
                        passStr}, this.onEndGetGuideListDelegate, this.onGetGuideListCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap CreateChannel() {
            return new SmallInWbsSoapClientChannel(this);
        }
        
        private class SmallInWbsSoapClientChannel : ChannelBase<SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap>, SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap {
            
            public SmallInWbsSoapClientChannel(System.ServiceModel.ClientBase<SmallInvestment.PhoneWeb.SmallInvestmentWs.SmallInWbsSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetBankList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetBankList", _args, callback, asyncState);
                return _result;
            }
            
            public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListResponse EndGetBankList(System.IAsyncResult result) {
                object[] _args = new object[0];
                SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListResponse _result = ((SmallInvestment.PhoneWeb.SmallInvestmentWs.GetBankListResponse)(base.EndInvoke("GetBankList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLoanRateList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLoanRateList", _args, callback, asyncState);
                return _result;
            }
            
            public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListResponse EndGetLoanRateList(System.IAsyncResult result) {
                object[] _args = new object[0];
                SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListResponse _result = ((SmallInvestment.PhoneWeb.SmallInvestmentWs.GetLoanRateListResponse)(base.EndInvoke("GetLoanRateList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWageList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetWageList", _args, callback, asyncState);
                return _result;
            }
            
            public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListResponse EndGetWageList(System.IAsyncResult result) {
                object[] _args = new object[0];
                SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListResponse _result = ((SmallInvestment.PhoneWeb.SmallInvestmentWs.GetWageListResponse)(base.EndInvoke("GetWageList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetGuideList(SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetGuideList", _args, callback, asyncState);
                return _result;
            }
            
            public SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListResponse EndGetGuideList(System.IAsyncResult result) {
                object[] _args = new object[0];
                SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListResponse _result = ((SmallInvestment.PhoneWeb.SmallInvestmentWs.GetGuideListResponse)(base.EndInvoke("GetGuideList", _args, result)));
                return _result;
            }
        }
    }
}
